<?php use Jegulnomic\Systems\Template\Flash;?>

<?php $this->extend('src/Templates/base_webapp.phtml') ?>
<?php $this->block('modal') ?>
    <form class="main-form first" action="/remittance-operator/login" method="post">
        <div class="main-form__title">
            <?php if ($this->telegram_user_photo_path): ?>
                <img src="/remittance-operator/profile-picture-provider?path=<?= $this->telegram_user_photo_path ?>" />
            <?php endif; ?>

<!--            <h1> Login</h1>-->
<!--            <h2>Войдите для продолжения работы в системе</h2>-->
        </div>

        <?=Flash::flash('login') ?>

        <div class="main-form__body">
            <input class="main-form__body--input"
                   name="telegram_user_id"
                   id="telegram-user-id"
                   type="hidden"
                   placeholder="Telegram user id"
                   readonly="readonly"
                   value="<?= $_REQUEST['telegram_user_id'] ?>" /> &#x9;
            <input class="main-form__body--input"
                   name="telegram_username"
                   id="telegram-username"
                   type="text"
                   readonly="readonly"
                   placeholder="Telegram username"
                   value="<?= $_REQUEST['telegram_username'] ?>"
            />
            <input class="main-form__body--input"
                   name="password"
                   type="password"
                   placeholder="Password" />&#x9; &#x9;
            <button class="btn full_btn" name="submit-login">Login</button>
        </div>
    </form>
<?php $this->endblock() ?>